from typing import List

from services.data_collection import MarketNewsItem


async def generate_sector_report_markdown(
    sector: str, news_items: List[MarketNewsItem]
) -> str:
    """
    Generate a structured markdown report for a given sector.

    In the final implementation, this function will:
    - Take structured market data (news, trends, policies)
    - Call an LLM (e.g., Gemini) with a carefully designed prompt
    - Use the LLM response to build a richer report

    For now, it uses a simple rule-based template that incorporates
    the collected news items.
    """

    sector_title = sector.title()

    news_section_lines = [
        "## Recent Market News",
        "",
    ]

    if news_items:
        news_section_lines.extend(item.to_bullet_point() for item in news_items)
    else:
        news_section_lines.append(
            "- No recent news items found in the stub implementation."
        )

    news_section = "\n".join(news_section_lines)

    report_markdown = f"""# Trade Opportunities Report: {sector_title}

## Overview

This is an initial, rule-based overview for the **{sector}** sector in India.
In the final implementation, this section will be generated by an LLM such as Gemini,
summarizing the current market landscape, demand drivers, and competitive dynamics.

## Key Opportunities

- Opportunity 1: Illustrative example opportunity in the {sector} sector, such as expanding into underpenetrated domestic regions.
- Opportunity 2: Illustrative example opportunity leveraging export demand for Indian {sector} capabilities.
- Opportunity 3: Illustrative example opportunity using digital transformation or automation within the {sector} value chain.

{news_section}

## Risks and Challenges

- Risk 1: Example regulatory or policy uncertainty affecting the {sector} sector.
- Risk 2: Example market or pricing pressure from global competitors.
- Risk 3: Example operational risks such as supply chain disruptions or technology adoption barriers.

## Suggested Next Steps for Investors or Businesses

- Validate these opportunities with more detailed, company-level and state-level data.
- Monitor upcoming policy announcements and incentive schemes related to the {sector} sector.
- Engage with domain experts and industry associations to refine the thesis.

## Conclusion

This report is currently generated using a deterministic template.
In the complete implementation, this section will be refined using LLM-driven insights
based on live market data for the {sector} sector in India.
"""

    return report_markdown